version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      storybook:
        patterns:
          - storybook
          - '@storybook/*'
          - chromatic
          - eslint-plugin-storybook
      eslint-prettier:
        patterns:
          - eslint
          - 'eslint-*'
          - '@eslint/*'
          - typescript-eslint
          - prettier
      types:
        patterns:
          - '@types/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
