import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import type { Meta, StoryObj } from '@storybook/react';

import { BarChart } from '../charts/BarChart';
import { ComboChart } from '../charts/ComboChart';
import { DonutChart } from '../charts/DonutChart';
import { HalfDonutChart } from '../charts/HalfDonutChart';
import { HistogramChart } from '../charts/HistogramChart';
import { LineChart } from '../charts/LineChart';
import { MapBubbleChart } from '../charts/MapBubbleChart';
import { PointerScale } from '../charts/PointerScale';
import { SankeyChart } from '../charts/SankeyChart';
import { Sparkline } from '../charts/Sparkline';
import { chartTokens } from '../theme/tokens';
import {
  barCategories,
  barSeries,
  comboBarSeries,
  comboCategories,
  comboLineSeries,
  distributionSegments,
  donutSegments,
  edFlowLinks,
  edFlowNodes,
  halfDonutRanges,
  histogramBins,
  lineCategories,
  lineSeries,
  pointerRanges,
  riskDistributionSegments,
  sparklineLabels,
  sparklineValues,
  stackedBarSeries
} from './storyData';
import { generateLineCategories, generateLineSeries, generateMapPoints } from './seededData';
import { ProfiledChart } from './utils/ProfilerCounter';

const meta = {
  title: 'Stress/Performance Baseline',
  parameters: {
    layout: 'fullscreen',
    chromatic: {
      delay: 500,
      pauseAnimationAtEnd: true
    }
  }
} satisfies Meta;

export default meta;

type Story = StoryObj<typeof meta>;
const recaptureCategories = ['18-30', '31-45', '46-60', '61-75', '75+'];
const lineReferenceLines = [
  { value: 900, label: 'Target', color: chartTokens.categorical.primary }
];

function StressTile({ label, children }: { label: string; children: ReactNode }) {
  return (
    <ProfiledChart label={label}>
      <div
        style={{
          minHeight: 260,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center'
        }}
      >
        {children}
      </div>
    </ProfiledChart>
  );
}

function Stress12ChartsStory() {
  const [version, setVersion] = useState(0);
  const stressMapPoints = useMemo(() => generateMapPoints('stress-map-small', 48), []);

  return (
    <div style={{ minHeight: '100vh', background: '#f6f8fb', padding: 32 }}>
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: 20
        }}
      >
        <div>
          <h1 style={{ margin: 0, fontSize: 22 }}>Stress 12 Charts</h1>
          <p style={{ margin: '6px 0 0', color: '#6b7280' }}>
            Stable props, parent render version {version}
          </p>
        </div>
        <button
          type="button"
          onClick={() => setVersion((current) => current + 1)}
          style={{
            border: '1px solid #cfd6dd',
            borderRadius: 6,
            background: '#fff',
            cursor: 'pointer',
            fontWeight: 600,
            padding: '8px 12px'
          }}
        >
          Re-render parent
        </button>
      </div>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
          gap: 20
        }}
      >
        <StressTile label="Grouped bar">
          <BarChart
            title="Revenue generated by payer"
            categories={barCategories}
            series={barSeries}
            width="100%"
            plotWidth={320}
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Stacked bar">
          <BarChart
            title="RAF recapture mix"
            categories={recaptureCategories}
            series={stackedBarSeries}
            layout="stacked"
            width="100%"
            plotWidth={320}
            showTotalLabels
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Distribution">
          <BarChart
            title="Opportunity per patient"
            mode="distribution"
            distributionSegments={distributionSegments}
            width="100%"
            plotWidth={320}
            showSegmentLabels
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Combination">
          <ComboChart
            title="Revenue by age group"
            categories={comboCategories}
            barSeries={comboBarSeries}
            lineSeries={comboLineSeries}
            width="100%"
            plotWidth={320}
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Donut">
          <DonutChart
            title="Revenue Goal"
            segments={donutSegments}
            centerLabel="100M"
            centerSubLabel="Target"
            width="100%"
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Half donut">
          <HalfDonutChart
            title="ED Outreach"
            value={71}
            ranges={halfDonutRanges}
            centerLabel="71%"
            centerSubLabel="(845 of 1,190)"
            width="100%"
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Histogram">
          <HistogramChart
            title="PCP visits"
            bins={histogramBins}
            width="100%"
            plotWidth={320}
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Line">
          <LineChart
            title="Average PMPM Trend"
            categories={lineCategories}
            series={lineSeries}
            width="100%"
            plotWidth={320}
            showHoverCard={false}
            referenceLines={lineReferenceLines}
          />
        </StressTile>

        <StressTile label="Map">
          <MapBubbleChart
            title="Hospital Network"
            points={stressMapPoints}
            width="100%"
            plotWidth={340}
            plotHeight={220}
            showHoverCard={false}
            showMenu={false}
          />
        </StressTile>

        <StressTile label="Pointer scale">
          <PointerScale
            title="HHS-HCC"
            value={23}
            ranges={pointerRanges}
            width="100%"
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Sankey">
          <SankeyChart
            title="ED patient flow"
            nodes={edFlowNodes}
            links={edFlowLinks}
            width="100%"
            plotWidth={360}
            plotHeight={230}
            showHoverCard={false}
          />
        </StressTile>

        <StressTile label="Sparkline">
          <div style={{ width: 360, padding: 28, borderRadius: 12, background: '#fff' }}>
            <h3 style={{ margin: '0 0 16px', fontSize: 16 }}>Average PMPM</h3>
            <Sparkline
              values={sparklineValues}
              labels={sparklineLabels}
              width={300}
              height={96}
              showAreaFill
              showDots
              showHoverCard={false}
            />
          </div>
        </StressTile>
      </div>
    </div>
  );
}

function LargeLine1kStory() {
  const categories = useMemo(() => generateLineCategories(1000), []);
  const series = useMemo(() => generateLineSeries('line-1k', 1000), []);

  return (
    <div style={{ minHeight: '100vh', background: '#f6f8fb', padding: 48 }}>
      <LineChart
        title="Large line - 1k points"
        categories={categories}
        series={series}
        width={900}
        plotWidth={760}
        plotHeight={300}
        showHoverCard={false}
        yAxis={{ title: 'PMPM' }}
      />
    </div>
  );
}

function LargeLine10kStory() {
  const categories = useMemo(() => generateLineCategories(10000), []);
  const series = useMemo(() => generateLineSeries('line-10k', 10000), []);

  return (
    <div style={{ minHeight: '100vh', background: '#f6f8fb', padding: 48 }}>
      <LineChart
        title="Large line - 10k points"
        categories={categories}
        series={series}
        width={900}
        plotWidth={760}
        plotHeight={300}
        showHoverCard={false}
        yAxis={{ title: 'PMPM' }}
      />
    </div>
  );
}

function LargeMapBubbleStory() {
  const points = useMemo(() => generateMapPoints('map-200', 220), []);

  return (
    <div style={{ minHeight: '100vh', background: '#f6f8fb', padding: 48 }}>
      <MapBubbleChart
        title="Large map bubble - 220 facilities"
        points={points}
        width={900}
        plotWidth={760}
        plotHeight={430}
        showHoverCard={false}
        showLegend
        showMenu={false}
      />
    </div>
  );
}

export const Stress12Charts: Story = {
  render: () => <Stress12ChartsStory />
};

export const LargeLine1k: Story = {
  render: () => <LargeLine1kStory />
};

export const LargeLine10k: Story = {
  parameters: {
    chromatic: {
      disableSnapshot: true
    }
  },
  render: () => <LargeLine10kStory />
};

export const LargeMapBubble: Story = {
  render: () => <LargeMapBubbleStory />
};

export const DistributionStress: Story = {
  render: () => (
    <div style={{ minHeight: '100vh', background: '#f6f8fb', padding: 48 }}>
      <BarChart
        title="Risk distribution"
        mode="distribution"
        distributionSegments={riskDistributionSegments}
        showScale
        showSegmentLabels
        width={900}
        plotWidth={760}
        showHoverCard={false}
      />
    </div>
  )
};
